version: 2.1

jobs:
  wait-on-nodes:
    docker:
      - image: cimg/base:stable
    resource_class: small
    parallelism: 3
    steps:
      - run:
          name: some operation
          command: |
            # sleep 10s x $CIRCLE_NODE_INDEX env var
            # NOTE: $CIRCLE_NODE_INDEX is zero-based
            sleep $((($CIRCLE_NODE_INDEX + 1) * 10))
      - run:
          name: fan-in summary operation
          command: |
            # NOTE: only to be run on 1st node
            if [ 0 -eq $CIRCLE_NODE_INDEX ]; then
              # wait on other nodes...
              while true; do
                if $(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/job/${CIRCLE_BUILD_NUM}" | jq -e '.parallel_runs[1:] | map(select(.status == "running")) | length == 0'); then
                  echo "all nodes completed; either success, failed or canceled"
                  break
                else
                  echo "some nodes are still running... wait out..."
                  sleep 5
                fi
              done
            fi

workflows:
  mark-job-succeed:
    jobs:
      - wait-on-nodes
